apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-gateway.fullname" . }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "mcp-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
